version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/prtea
    binary: prtea
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat.*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix.*:+.*$"
      order: 10
    - title: Other work
      order: 999

brews:
  - name: prtea
    repository:
      owner: shhac
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/shhac/prtea"
    description: "A TUI for reviewing GitHub pull requests"
    license: "MIT"
    install: |
      bin.install "prtea"
    test: |
      system "#{bin}/prtea", "--version"
    skip_upload: auto

release:
  footer: |
    ---
    **Full Changelog**: https://github.com/shhac/prtea/compare/{{ .PreviousTag }}...{{ .Tag }}
